dbca-wa/oim-cms

- core/templates/f6-base.html
- registers/models.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/2)
> updated foundation

- registers/models.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/13)
> Fix bug in SecondaryLocation save method.

- oim_cms/api.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/14)
> Fix bug in OptionResource data_cost_centre method.

- oim_cms/api.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/15)
> Return user's photo and photo_ad as absoulte url for user rest api

- tracking/models.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/16)
> tracking.DepartmentUser: make update_photo_ad more robust

- core/templates/f6-base.html
- oim_cms/api.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/17)
> Added data_location to OptionResource

- core/templates/core/tags/breadcrumbs.html
- core/templates/f6-base.html
- core/views.py
- oim_cms/api.py
- oim_cms/urls.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/18)
> Add API endpoint for user profile changes

- oim_cms/api.py
- registers/models.py
- tracking/models.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/19)
> Meta classes fir EC2, Process, Location models. Added data_division to OptionResource.

- oim_cms/api.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/21)
> Added notes and working_hours output to UserResource class.

- oim_cms/api.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/22)
> Added org_unit__secondary_location__name to UserResource class.

- core/views.py
- oim_cms/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/23)
> core.auth_ip: expose KMI roles string

- core/static/css/f6_oim_cms.css
- core/static/css/f6_oim_cms.scss
- core/templates/core/tags/include_content.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/26)
> Added .hide-for-print to f6_oim_cms.scss

- postgrest/migrations/0001_initial.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/27)
> postgrest: pin migrations to occur after tracking/registers

- registers/models.py
- tracking/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/33)
> Added edit warning note in DepartmentUser ModelAdmin class.

- catalogue/admin.py
- catalogue/api.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/36)
> updating styles currently in the catalogue service

- catalogue/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/39)
> Changed the api endpoint for records to /catalogue/api/records

- catalogue/api.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/40)
> Add properties 'sld','qml','lyr' for default style in record

- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/41)
> Create default styles if none exists

- registers/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/45)
> Added some admin functionality for BusinessFunction and BusinessProcess models

- registers/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/46)
> Added missing mtd, rto, rpo fields on ITSystemAdmin.

- oim_cms/api.py
… http method  to detail handler
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/47)
> For whoami resource,use request.user to authenticate request, and map all http method to detail handler

- catalogue/api.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/48)
> Automatically choose a default style, if no default style is configured

- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/49)
> Set the automatically choosed layer as default layer in style table

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/50)
> Change the comments

- catalogue/admin.py
- catalogue/forms.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/51)
> Change record's list and edit page .

- catalogue/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/52)
> Added identifier to the records serializer

- catalogue/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/54)
> Remove embeded style form from record edit page for wms layer

- tracking/admin.py
- tracking/models.py
- tracking/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/57)
> Override DepartmentUserAdmin save_model method to log changes to some object fields

- catalogue/pycswsettings.py
- catalogue/urls.py
- catalogue/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/59)
> Customize SQLAlchemy's mapper to determine the primary key for view

- catalogue/pycswsettings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/60)
> Use the default value if db connection paramters are missing

- catalogue/api.py
- catalogue/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/62)
> Add the aws resources serializer

- catalogue/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/63)
> added format_date request parameter in record serializer

- catalogue/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/64)
> added url in record serializer

- catalogue/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/65)
> display style raw content only if borg in request

- catalogue/api.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/69)
> Create record links

- catalogue/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/70)
> Modified OWS serializer

- tracking/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/71)
> Added update reference to logged information on DepartmentUser name field changes

- catalogue/api.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/74)
> Define base url in ows resource

- catalogue/api.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/75)
> Format bounding box for ows resource link

- catalogue/api.py
Use http request parameter 'style_content' to output style raw content
Add parameter "style_content" to serializer indicate whether exporting style content.
Always add publication_date and modifyed with default date format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/76)
> Use http request parameter 'style_content' to output style raw content

- catalogue/api.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/77)
> Added read only ows in record serializer

- catalogue/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/78)
> Determine the ows resource in record serializer

- catalogue/admin.py
- catalogue/api.py
- oim_cms/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/79)
> Add publish feature for record

- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/80)
> Install dpaw-utils's new version 0.3a10

- catalogue/models.py
- oim_cms/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/81)
> Fix issue with creating WFS link

- catalogue/admin.py
- catalogue/api.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/82)
> Transform the bbox format to wkt format

- catalogue/api.py
- catalogue/mappings.py
- catalogue/models.py
- catalogue/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/84)
> Subclass Csw to override _write_record method

- catalogue/admin.py
- catalogue/api.py
- catalogue/mappings.py
- catalogue/models.py
- catalogue/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/85)
> Generate the gwc supported preview url

- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/86)
> remove print statements

- catalogue/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/87)
> Added import for write_boundingbox in the views

- catalogue/admin.py
- catalogue/api.py
- catalogue/models.py
- catalogue/views.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/88)
> Using pyproj to transform the original crs to target crs specified in wms endpoint

- catalogue/data/epsg
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/89)
> Add 900913's proj4 string

- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/90)
> Added metadata_link to record

- catalogue/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/91)
> Rename util from sqlalchemy to sqlalchemy_util

- catalogue/api.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/92)
> Added metadata_link to record serializer

- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/93)
> Add version and type to metadata link

- catalogue/admin.py
- catalogue/api.py
- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/94)
> Support multiple gwc endpoints

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/97)
> Added contingency plan fields to ITSystem API response.

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/99)
> Make ITSystemResource API response return contingency_plan_status display value

- oim_cms/settings.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/100)
> Increment wagtail version to 1.4.3, Django to 1.9.5.

- core/models.py
- registers/admin.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/104)
> Added wagtail-markdown to reqs, added MarkdownMarkdown block.

- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/106)
> Bump wagtail version to 1.4.5.

- core/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/107)
> Comment out wagtail-markdown temporarily to avoid borking the CMS.

- oim_cms/settings.py
- requirements.txt
- tracking/admin.py
- tracking/templates/tracking/alesco_import.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/108)
> Added custom view on DepartmentUserAdmin to import Alesco data from spreadsheet.

- tracking/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/110)
> Added more options to ACCOUNT_TYPE field on DepartmentUser model.

- manage.py
- oim_cms/__init__.py
- oim_cms/celery.py
- oim_cms/settings.py
- oim_cms/wsgi.py
- requirements.txt
- tracking/admin.py
- tracking/tasks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/112)
> Moved Alesco spreadsheet uploaded into an async Celery task.

- tracking/admin.py
- tracking/models.py
- tracking/templates/admin/tracking/departmentuser/change_list.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/113)
> Manually generate alesco_data_pretty HTML output

- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/117)
> Bumped wagtail to 1.5.2 (migration req'd) and Django to 1.9.7.

- tracking/management/commands/pdq_load_data.py
- tracking/management/commands/sync_freshdesk_contacts.py
- tracking/utils.py
- tracking/utils_pdq.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/118)
> Added tracking/utils_pdq.py to load Computers from PDQ Inventory scan data

- tracking/utils_pdq.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/119)
> Update pdq_load_hardware function to create/link Hardware objects to Computers

- tracking/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/124)
> Added additional fields to DepartmentUser export output CSV.

- oim_cms/settings.py
- registers/admin.py
- registers/templates/admin/registers/itsystem/change_list.html
- tracking/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/125)
> Added admin view to export IT Systems.

- registers/admin.py
- registers/templates/admin/registers/itsystem/change_list.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/126)
> Correctly override admin changelist template for ITSystem.

- registers/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/129)
> Added count of affected IT Systems to ITSystemhardwareAdmin list_display.

- tracking/utils_freshdesk.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/131)
> Bugfix in freshdesk_sync_contacts function (optional dict key).

- core/views.py
- oim_cms/settings.py
- registers/admin.py
- registers/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/133)
> Added request_access field to ITSystemAdmin class

- .gitignore
- .travis.yml
- registers/admin.py
- registers/models.py
- requirements.txt
- tracking/management/commands/cache_freshdesk_tickets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/140)
> Reduce logging in cache_freshdesk_tickets, added .travis.yml, additional registers models docstrings.

- oim_cms/api.py
- tracking/models.py
- tracking/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/141)
> Added password_age_days to UserResource API response.

- catalogue/admin.py
- catalogue/api.py
- catalogue/models.py
Add column 'publish ?' in admin list page; 
Update modified when record data(including sld style)is changed
Make modified field nullable in catalogue rest api.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/143)
> Add column 'publish ?' in admin list page; 

- catalogue/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/149)
> Remove properties 'workspace','name' before saving record, and save styles for new record

- catalogue/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/151)
> Set modified to now if geoserver related columns are changed; fix a default style setting bug.

- oim_cms/api.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/155)
> Changes to API responses for Address List page. Update Wagtail version to v1.5.3.

- core/templates/f5-base.html
- core/templates/f6-base.html
- oim_cms/context_processors.py
- oim_cms/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/157)
> Added application version to base templates & context.

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/158)
> Moved preferred_name value from VALUES_ARGS to COMPACT_ARGS in DepartmentUser API

- core/models.py
- registers/admin.py
- registers/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/167)
> Added 'original' image format for rich text editor.

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/168)
> Added MINIMAL_ARGS to UserResource class for faster API response.

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/169)
> Alter UserResource API filtering (performance).

- tracking/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/170)
> Fix bug in tracking/models.py (save on CommonFields).

- core/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/171)
> Support shared_id as credential in basic auth  for auth_ip request

- core/templates/core/tags/f6_top_menu.html
- core/templates/f6-base-vue.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/173)
> CSS fix for top menu search form in f6_base_vue template

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/174)
> Add account_type to UserResource API output.

- registers/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/175)
> Update OrgUnitAdmin users() callable to return count of active DepartmentUsers only

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/176)
> Added data_org_unit to OptionResource model.

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/177)
> Refactor UserResource API so 'all' parameter does not exclude shared/role-based accounts.

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/178)
> Include shared and role-based accounts in org_structure API output.

- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/179)
> Bump Wagtail version to 1.6.

- oim_cms/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/180)
> Added populate_groups query param to the org_structure API output.

- catalogue/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/181)
> Export id field in /catalogue/api/records rest api

- registers/models.py
- tracking/utils_freshdesk.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/182)
> Added is_support_category and match_it_system methods to ITSystem model.

- registers/admin.py
- registers/models.py
- tracking/utils_freshdesk.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/183)
> Add FreshdeskTicketAdmin class

- core/templates/f5-base.html
- core/templates/f6-base-vue.html
- core/templates/f6-base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/184)
> Added modernizr.js to all base templates.

- registers/models.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/186)
> Update to handle Unicode in Freshdesk objects.

- registers/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/187)
> Added additional OrgUnit type choices.

- registers/models.py
- tracking/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/189)
> Exclude units with 0 members from org structure API output. Extra fields in DepartmentUser CSV export.

- oim_cms/test_api.py
- registers/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/198)
> Added unit tests for OptionResource methods

- core/views.py
- oim_cms/api.py
- oim_cms/test_api.py
- oim_cms/utils.py
- organisation/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/201)
> Factored UserResource and profile into organisation/api.py.

- oim_cms/api.py
- oim_cms/test_api.py
- organisation/api.py
- tracking/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/203)
> Moved LocationResource and EC2InstanceResource classes to their own apps

- organisation/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/208)
> Bugfix: restore is_authenticated method returning True on DepartmentUserResource to allow AD sync script to work

- oim_cms/api.py
- oim_cms/settings.py
- registers/admin.py
- registers/api.py
- registers/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/216)
> Added custodian name & email to ITSystemResource output for dependencies

- organisation/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/217)
> Alter DepartmentUserResource class: added ad_deleted parameter.

- organisation/api.py
- organisation/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/220)
> Updates to the DepartmentUserResource class API responses

- README.md
- core/test.py
- registers/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/225)
> ITSystemResource detail response return cost_centre details in preference to owner.cost_centre

- organisation/admin.py
- organisation/api.py
- organisation/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/230)
> Added secondary CC, OrgUnit and Location to org_structure API output.

- oim_cms/test_api.py
- oim_cms/utils.py
- organisation/admin.py
- organisation/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/232)
> Refactor DepartmentUserResource (bugfix, refactor create & update views)

- organisation/admin.py
- organisation/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/233)
> Add a second, delayed save to DepartmentUserAdmin so that org_data is correct

- organisation/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/234)
> Organisation/api.py fixes: try/except on update, prevent emails appearing > once in org_structure groups

- forms/api.py
- forms/test_views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/236)
> Fix broken test.

- oim_cms/test_api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/239)
> Fix outdated unit test.

- assets/admin.py
- assets/api.py
- oim_cms/api.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/240)
> Additional config for HardwareAssetAdmin, basic API endpoint for HardwareAsset.

- assets/import_legacy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/241)
> Fix Import Script Location_ID Field Populating Problem

- assets/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/242)
> Rearrange HardwareAssetAdmin fields.

- assets/import_legacy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/244)
> Legacy import script update

- assets/import_history.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/248)
> Import reversion history from old to new

- knowledge/templates/knowledge/itsystem_detail.html
- knowledge/templates/knowledge/itsystem_form.html
- knowledge/templates/knowledge/itsystem_register.html
- knowledge/test_views.py
- knowledge/urls.py
- knowledge/views.py
- registers/admin.py
- registers/test_admin.py
- registers/test_models.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/255)
> ITSystemAdmin bugfix. ITSystemDetail view.

- core/templates/core/tags/f6_top_menu.html
- core/templates/f6-base.html
- oim_cms/static/css/maincontent.css
- oim_cms/static/css/mobilemenu.css
- oim_cms/static/css/topbar.css
- oim_cms/static/js/topbar.js
More UI Improvement/fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/258)
> More UI Improvement/fixes

- core/models.py
- core/templates/core/tags/include_content.html
- core/templates/core/tags/top_menu.html
- core/templates/f5-base.html
- core/templates/f6-base.html
- oim_cms/settings.py
- oim_cms/static/js/topbar.js
OIM CMS Improvements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/259)
> OIM CMS Improvements

- organisation/api.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/267)
> Increment wagtail to v1.10.1. 	Require no caching for certain DepartmentUserResource responses.

- organisation/api.py
- registers/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/269)
> Added platforms to ITSystemResource API response

- .travis.yml
- oim_cms/settings.py
- organisation/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/270)
> Implement Postgres as search backend

- registers/api.py
- tracking/management/commands/salt_load_data.py
- tracking/utils_pdq.py
- tracking/utils_salt.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/271)
> Added salt_load_data management command. Bug fix: add VALUES_ARGS to ITSystemResource to unbreak CSV endpoint.

- oim_cms/api.py
- oim_cms/test_api.py
- registers/admin.py
- registers/api.py
- registers/templates/admin/itsystemdependency_reports.html
- registers/templates/admin/registers/itsystemdependency/change_list.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/273)
> Add oim_internal_only to ITSystemResource output. Added reports to output IT System dependencies.

- core/templates/f6-base-vue.html
- core/templates/f6-base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/277)
> Update URLs in header DPaW > DBCA.

- core/templates/core/tags/top_menu.html
- knowledge/templates/itsystemform.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/278)
> Changed missed refs to www.dpaw.wa.gov.au URL.

- organisation/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/285)
> Exclude role-based and shared accounts from org_structure API endpoint.

- organisation/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/290)
> Added expiry_date exclude from users API endpoint.

- core/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/295)
> Alter core/views.py auth: avoid exception where UserSession does not exist

- registers/admin.py
- registers/api.py
- registers/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/297)
> Refactor ITSystemEventResource response to send datetime as local.

- organisation/api.py
- organisation/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/300)
> Alter DepartmentUserResource prepare method to return datetimes with timezone information.

- .travis.yml
- assets/admin.py
- assets/import_assets.py
- assets/models.py
- assets/utils.py
- organisation/admin.py
- organisation/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/302)
> Functions to import legacy hardware assets.

- assets/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/309)
> HardwareAssetAdmin: search serial number and hardware model name.

- assets/utils.py
- organisation/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/310)
> Updates to HardwareAssetAdmin and DepartmentUser API detail endpoint.

- organisation/api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/311)
> Better info/exception logging for DepartmentUserResource create & update methods

- registers/admin.py
- registers/test_admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/316)
> Unit test registers/admin custom view responses

- .travis.yml
- catalogue/test_api.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/317)
> Additional unit tests. Update wagtail and djangorestframework-filter libraries.

- tracking/utils_pdq.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/319)
> Bugfix utils_pdq: PDQ CSV output doesn't contain CPU info any more.

- organisation/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/322)
> DepartmentUserAdmin export: output all objects (not just active).

- README.md
- assets/admin.py
- registers/admin.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/parksandwildlife/oim-cms/324)
> Increment wagtail version. HardwareAsset: admin search on location, assigned user, extra fields in CSV output.

- organisation/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/330)
> Update DepartmentUser.org_data to output CC org_position name.

- README.md
- core/models.py
- oim_cms/settings.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/333)
> Bugfix: send_mail issue with body as bytes, add gevent to req's. Update README.

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/336)
> Update Travis config (remove coveralls).

- .s2i/environment
- .travis.yml
- README.md
- gunicorn.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/337)
> Add APP_CONFIG to .s2i/environment, update Travis config.

- oim_cms/settings.py
- oim_cms/wsgi.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/338)
> Factor out Unipath, swap dj-static for whitenoise package.

- .s2i/environment
- manage.py
- oim_cms/settings.py
- oim_cms/wsgi.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/339)
> Refactor logging, set SECRET_KEY default for image builds.

- .s2i/environment
- .travis.yml
- Dockerfile
- oim_cms/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/341)
> Update Dockerfile. Remove custom handler404 in urls.

- core/templates/f5-base.html
- core/templates/f6-base-vue.html
- core/templates/f6-base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/344)
> Remove temporary callout notification at the top of base templates.

- core/templates/f5-base.html
- core/templates/f6-base-vue.html
- core/templates/f6-base.html
Missed some rebranding
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/346)
> templates: replace DPaW with DBCA

- oim_cms/settings.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/347)
> Updated wagtail to 2.5

- Dockerfile
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/348)
> Update wagtail & Dockerfile

- manage.py
- oim_cms/settings.py
- oim_cms/wsgi.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/349)
> Factor out django-confy, update Django to 2.1.10.

- Dockerfile
- oim_cms/settings.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/350)
> Update wagtail to 2.6.1

- core/templates/emailform.html
- core/views.py
- oim_cms/settings.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/351)
> Update user account form. Update Django & wagtail versions.

- .travis.yml
- oim_cms/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/352)
> Travis CI updates

- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/354)
> Update wagtail, Pillow

- .travis.yml
- Dockerfile
- oim_cms/settings.py
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/356)
> Update wagtail to 2.7.1, update .travis.yml, update Django to 2.2.9

- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/361)
> Update wagtail to mitigate XSS vuln

- .travis.yml
- oim_cms/settings.py
- poetry.lock
- pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/373)
> Increment wagtail to 2.12.3, bump Django and other library versions

- oim_cms/settings.py
- poetry.lock
- pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/375)
> Increment Django, wagtail, Pillow versions.

- Dockerfile
- core/static/css/f6_oim_cms.css
- poetry.lock
- pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/382)
> CSS rule to hide placeholder text on print, update wagtail version.

- .github/workflows/docker-publish.yml
- Dockerfile
- core/apps.py
- core/templatetags/core_tags.py
- oim_cms/middleware.py
- oim_cms/settings.py
- oim_cms/static/css/selectsize.default.css
- oim_cms/wsgi.py
- poetry.lock
- pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dbca-wa/oim-cms/384)
> Update Django to 3.2, Python to 3.9, switch dj-static for whitenoise, add Github workflow.
